### ISSUE TITLE
Crash of appearance-settings, if 'alarms & reminders'-permission is not allowed (@Android 14)

### ISSUE THREAD

**Issue by revuwa** [artyommironov/nanji#29]
If I click on:
![image](https://github.com/artyommironov/nanji/assets/7300276/13866614-5889-4471-884f-79f31d9fd2a0)
the app crashes with the following log:

```
type: crash
osVersion: google/{name}/{name}:14/UD1A.230803.041/2023102300:user/release-keys
package: com.kazufukurou.nanji:41
process: com.kazufukurou.nanji
processUptime: 1378 + 177 ms
installer: com.machiav3lli.fdroid

java.lang.RuntimeException: Unable to start receiver com.kazufukurou.nanji.ui.WidgetProvider: java.lang.SecurityException: Caller com.kazufukurou.nanji needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4469)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2263)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.SecurityException: Caller com.kazufukurou.nanji needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:311)
	at android.app.AlarmManager.setImpl(AlarmManager.java:1093)
	at android.app.AlarmManager.setImpl(AlarmManager.java:1045)
	at android.app.AlarmManager.setExact(AlarmManager.java:809)
	at com.kazufukurou.nanji.ui.WidgetProvider.h(SourceFile:40)
	at com.kazufukurou.nanji.ui.WidgetProvider.i(SourceFile:247)
	at com.kazufukurou.nanji.ui.WidgetProvider.onUpdate(SourceFile:9)
	at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:71)
	at com.kazufukurou.nanji.ui.WidgetProvider.onReceive(SourceFile:6)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4460)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.alarm.AlarmManagerService$5.set(AlarmManagerService.java:2981)
	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:181)
	at android.os.Binder.execTransactInternal(Binder.java:1368)
	at android.os.Binder.execTransact(Binder.java:1299)
```

If I manually give the needed permission:
![image](https://github.com/artyommironov/nanji/assets/7300276/0e6186e7-56d1-4f01-8fdb-550ffd0fff7a)
and restart the app, it works pretty well.

Probably it's a good idea to ask for this permission on (first) app startup. What do you think?

**Comment by inson1** [comment]
For me it doesnt need any permissons and it doesnt crashes.

I think it shouldnt need Alarm permisson.

Device: Xiaomi Redmi note 8 Pro
OS: Android 11 MIUI 12.5.7
Version: 1.4.2
Language: English

**Comment by inson1** [comment]
only thing I found about alarm in android 14 docs
https://source.android.com/docs/setup/about/android-14-release

is this 

"Full-screen intent limits
To prevent ad spam and credential phishing, starting with Android 14, the default [USE_FULL_SCREEN_INTENT](https://developer.android.com/reference/android/Manifest.permission#USE_FULL_SCREEN_INTENT) permission to send full-screen notifications can be granted only to apps that provide calling and alarm functionalities. See [Full-screen intent limits](https://source.android.com/docs/core/permissions/fsi-limits) for more information."

But I dont think we are using it. And if yes then I dont get it why we need it in appearance

**Comment by inson1** [comment]
We need alarms for something, idk why 
![image](https://github.com/artyommironov/nanji/assets/75314629/2e48e6ef-0e54-4be3-94d7-edee9bc04706)

**Comment by inson1** [comment]
ok, now I get it - "Open system alarm app on tap"

**Comment by inson1** [comment]
@revuwa Did you try creating the widget? Or did you do enything else? Before adding the permisson. Its just wierd that it would crash on appearance.

**Comment by inson1** [comment]
ok, this is why https://developer.android.com/about/versions/14/changes/schedule-exact-alarms
and this is I guess missing?

"Existing best-practices for the [SCHEDULE_EXACT_ALARM](https://developer.android.com/reference/android/Manifest.permission#SCHEDULE_EXACT_ALARM) permission still apply, including the following:

Check the permission with [canScheduleExactAlarms()](https://developer.android.com/reference/android/app/AlarmManager#canScheduleExactAlarms()) before scheduling exact alarms.
Set up your app to listen and properly react to the foreground broadcast [AlarmManager.ACTION_SCHEDULE_EXACT_ALARM_PERMISSION_STATE_CHANGED](https://developer.android.com/reference/android/app/AlarmManager#ACTION_SCHEDULE_EXACT_ALARM_PERMISSION_STATE_CHANGED), which the system sends when the user grants the permission."

**Comment by inson1** [comment]
We need that for updating widget. Isnt there other option for updating widgets? Without user permission?
I still dont get it why it crashed on appearance.
To be honest I dont know where should it be added - if only after opening the app is enough. Widgets shouldnt work.

**Comment by inson1** [comment]
@revuwa Btw this app doesnt yet even targets the andorid 14

**Comment by inson1** [comment]
@artyommironov what about using this instead https://github.com/CarterChen247/AlarmScheduler

**Comment by artyommironov** [comment]
On my device alarm permission is granted  by default on app fresh install, but if I disable it manually then I get same crash. 

> I still dont get it why it crashed on appearance.

@inson1 This is because when root settings screen goes background (close, switch to other screen) it calls widget update, which in turn schedules next update using the exact alarm.

>  Arent there other options for updating widgets?

> what about using this instead

[WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager#robust) seems can be used for this, I wil try it first.

**Comment by inson1** [comment]
@artyommironov You dont have Adroid 14 I guess. Its new thing in Android 14. It wasnt in basic release notes, but for example here it is https://developer.android.com/about/versions/14/behavior-changes-all

It was first thing I found, I dont care what we use, it just have do its work without any new permission from user.

**Comment by revuwa** [comment]
@artyommironov Thank you so much ❤️
